### Problem Statement:

To identify which customers will make a specific transaction in the future, irrespective of the amount of money transacted

## Importing Basic Libraries

In [3]:
import pandas as pd
import numpy as np

## Importing Training dataset

In [4]:
train=pd.read_csv('train.csv')

In [5]:
train.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

     var_7   ...     var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266   ...      4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338   ...      7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  14.6155   ...      2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  14.9250   ...      4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  19.2514   ...     -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 202 columns]

In [6]:
x_train=train

## Separating target values which we have to predict

In [7]:
y_train=train['target'].values

In [8]:
x_train.drop(['ID_code','target'],axis=1,inplace=True)

In [9]:
x_train.head()

var_0   var_1    var_2   var_3    var_4   var_5   var_6    var_7   var_8  \
0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187  18.6266 -4.9200   
1  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208  16.5338  3.1468   
2   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427  14.6155 -4.9193   
3  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428  14.9250 -5.8609   
4   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405  19.2514  6.2654   

    var_9   ...     var_190  var_191  var_192  var_193  var_194  var_195  \
0  5.7470   ...      4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  8.0851   ...      7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  5.9525   ...      2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  8.2450   ...      4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  7.6784   ...     -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 200 columns]

In [10]:
x_train=x_train.values

## Now we have x_train and y_train for training the model and testing its accuracy

In [11]:
x_train

array([[  8.9255,  -6.7863,  11.9081, ...,   8.5635,  12.7803,  -1.0914],
       [ 11.5006,  -4.1473,  13.8588, ...,   8.7889,  18.356 ,   1.9518],
       [  8.6093,  -2.7457,  12.0805, ...,   8.2675,  14.7222,   0.3965],
       ...,
       [ 11.2232,  -5.0518,  10.5127, ...,   8.7155,  13.8329,   4.1995],
       [  9.7148,  -8.6098,  13.6104, ...,  10.0342,  15.5289, -13.9001],
       [ 10.8762,  -5.7105,  12.1183, ...,   8.1857,  12.1284,   0.1385]])

In [12]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

## We have to find binary result So I am using Logistic regression model

In [13]:
import sklearn
from sklearn.linear_model import LogisticRegression

In [14]:
log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
y_train_pred=log_reg.predict(x_train)

In [16]:
y_train_pred

array([0, 1, 0, ..., 0, 0, 0])

In [17]:
log_reg.score(x_train,y_train)

0.91444

#### Above steps shows the model is working and it is predicting with 91% accuracy but there is one main problem in my laptop it took almost 2-3 minutes to fit the model due to its size. It has 200 features and to reduce time we have eliminate those features which are not contributing enough to predict the result but are just there and is of no significance.

# To eliminate features I am using Principal Component Analysis

In [19]:
from sklearn.decomposition import PCA 

In [105]:
pc=PCA(n_components=2)

### Fitting and transforming the training dataset into principal component of two features (which are non linearly correlated to each other)

In [106]:
principal_compo=pc.fit_transform(x_train)

In [107]:
principal_compo

array([[ -5.6064267 , -23.55621925],
       [ 34.87855547,  11.45194779],
       [ -4.79014402,  -0.30693149],
       ...,
       [ 36.84223171,   7.78847121],
       [ 30.23075344, -24.43151445],
       [ -5.99571528,   7.80140615]])

### Now fitting the model with pincipal component

In [108]:
log_reg.fit(principal_compo,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [109]:
pc_pred_train=log_reg.predict(principal_compo)

### Prediction score changed from 91% to 89.99% so this means accuracy reduced. Answer is no because we have to balance between the speed of predicting and correctness of predictions. In this model using principal components it took only 5 sec to compute as compare to 2-3 minutes before so we can accept this as we reduced huge amount of time but lost accuray by just 1% which is acceptable.

In [110]:
log_reg.score(principal_compo,y_train)

0.89951

### Job is not done yet as we have to check that how the model is behaving each time someone runs it.Is accuracy drops in different try??  so I have use cross_val_score to check the accuracy of model for 10 times and below is the result. 

In [111]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=log_reg, X=principal_compo, y=y_train, cv=10)
model_accuracy = accuracies.mean()
model_standard_deviation = accuracies.std()

In [112]:
accuracies

array([0.89950502, 0.89950502, 0.8995    , 0.8995    , 0.8995    ,
       0.8995    , 0.8995    , 0.8995    , 0.89954498, 0.89954498])

### Mean of accuracy is almost 90% with very very small standard deviation. So now we can say that prediction of model is good enough.

In [113]:
model_accuracy

0.8995100003995249

In [114]:
model_standard_deviation 

1.759636929631447e-05

## Below is the summary of model. You can see the p-value of x1 and x2 is very less than 0.05 by which we can say that the prediction is going to work

In [115]:
import statsmodels.api as sm
logit_model=sm.Logit(y_train,principal_compo)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.692996
         Iterations 3
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199998
Method:                           MLE   Df Model:                            1
Date:                Wed, 03 Apr 2019   Pseudo R-squ.:                  -1.125
Time:                        21:48:54   Log-Likelihood:            -1.3860e+05
converged:                       True   LL-Null:                       -65232.
                                        LLR p-value:                     1.000
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0011      0.000      5.475      0.000       0.001       0.002
x2            -0.0018      0.

### So how result will change if we change the number of components. Lets see!!

In [83]:
pc=PCA(n_components=3)

In [84]:
principal_compo=pc.fit_transform(x_train)

In [85]:
principal_compo

array([[ -5.60577804, -23.72231473,  -1.24699527],
       [ 34.87816181,  11.49571446,  -3.85630537],
       [ -4.78966104,  -0.42824315,  11.61467717],
       ...,
       [ 36.8421576 ,   7.73597525,  30.28756769],
       [ 30.23041915, -24.25565791,  25.0421733 ],
       [ -5.99486431,   7.7030697 ,  10.04244396]])

In [86]:
log_reg.fit(principal_compo,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [87]:
pc_pred_train=log_reg.predict(principal_compo)

In [88]:
log_reg.score(principal_compo,y_train)

0.89951

In [89]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=log_reg, X=principal_compo, y=y_train, cv=10)
model_accuracy = accuracies.mean()
model_standard_deviation = accuracies.std()

In [90]:
accuracies 

array([0.89950502, 0.89950502, 0.8995    , 0.8995    , 0.8995    ,
       0.8995    , 0.8995    , 0.8995    , 0.89954498, 0.89954498])

In [91]:
model_accuracy

0.8995100003995249

In [92]:
model_standard_deviation

1.759636929631447e-05

In [93]:
import statsmodels.api as sm
logit_model=sm.Logit(y_train,principal_compo)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.692980
         Iterations 3
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199997
Method:                           MLE   Df Model:                            2
Date:                Wed, 03 Apr 2019   Pseudo R-squ.:                  -1.125
Time:                        21:12:02   Log-Likelihood:            -1.3860e+05
converged:                       True   LL-Null:                       -65232.
                                        LLR p-value:                     1.000
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0011      0.000      5.475      0.000       0.001       0.002
x2            -0.0018      0.

### You can see above that by increasing the nmber of components by 1 it doesn't made much of a difference. P values of all the components are less than 0.05 but we are getting almost same result in terms of accuracy so why use this??right.

### Lets take a big jump and increase number of components to 10. What will happen now??lets see

In [94]:
pc=PCA(n_components=10)

In [95]:
principal_compo=pc.fit_transform(x_train)

In [96]:
principal_compo

array([[ -5.60644586, -23.56970964,  -1.8979458 , ..., -15.06061588,
         11.41121504,   1.91140577],
       [ 34.87812171,  11.43329375,  -3.7349499 , ...,  -2.92349773,
          8.080395  ,  18.86901207],
       [ -4.79015524,  -0.3782445 ,  11.37505343, ...,  -1.6852797 ,
         -4.17698535,   6.37036252],
       ...,
       [ 36.84232344,   7.71637965,  30.23716254, ...,  -5.07443379,
         -3.73106037,   2.40222404],
       [ 30.23091019, -24.39339283,  25.56945503, ...,   3.23953233,
          8.88064014,  11.239509  ],
       [ -5.99492124,   7.7281225 ,  10.11223016, ...,   6.32773478,
         -7.7345971 ,  -3.93947905]])

In [97]:
log_reg.fit(principal_compo,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [98]:
pc_pred_train=log_reg.predict(principal_compo)

In [99]:
log_reg.score(principal_compo,y_train)

0.89951

In [100]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=log_reg, X=principal_compo, y=y_train, cv=10)
model_accuracy = accuracies.mean()
model_standard_deviation = accuracies.std()

In [101]:
accuracies

array([0.89950502, 0.89950502, 0.8995    , 0.8995    , 0.8995    ,
       0.8995    , 0.8995    , 0.8995    , 0.89954498, 0.89954498])

In [102]:
model_accuracy

0.8995100003995249

In [103]:
model_standard_deviation

1.759636929631447e-05

In [104]:
import statsmodels.api as sm
logit_model=sm.Logit(y_train,principal_compo)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.692344
         Iterations 3
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199990
Method:                           MLE   Df Model:                            9
Date:                Wed, 03 Apr 2019   Pseudo R-squ.:                  -1.123
Time:                        21:14:07   Log-Likelihood:            -1.3847e+05
converged:                       True   LL-Null:                       -65232.
                                        LLR p-value:                     1.000
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0011      0.000      5.479      0.000       0.001       0.002
x2            -0.0018      0.

### Again we got almost same accuracy as before. So now we can conclude that we can use 2 component to predict the results which is very fast as compared to the original dataset and almost as accurate as it the original.

### Lets predict for test dataset.

In [116]:
test=pd.read_csv('test.csv')

In [117]:
test.head()

ID_code    var_0    var_1    var_2   var_3    var_4   var_5   var_6  \
0  test_0  11.0656   7.7798  12.9536  9.4292  11.4327 -2.3805  5.8493   
1  test_1   8.5304   1.2543  11.3047  5.1858   9.1974 -4.0117  6.0196   
2  test_2   5.4827 -10.3581  10.1407  7.0479  10.2628  9.8052  4.8950   
3  test_3   8.5374  -1.3222  12.0220  6.5749   8.8458  3.1744  4.9397   
4  test_4  11.7058  -0.1327  14.1295  7.7506   9.1035 -8.5848  6.8595   

     var_7   var_8   ...     var_190  var_191  var_192  var_193  var_194  \
0  18.2675  2.1337   ...     -2.1556  11.8495  -1.4300   2.4508  13.7112   
1  18.6316 -4.4131   ...     10.6165   8.8349   0.9403  10.1282  15.5765   
2  20.2537  1.5233   ...     -0.7484  10.9935   1.9803   2.1800  12.9813   
3  20.5660  3.3755   ...      9.5702   9.0766   1.6580   3.5813  15.1874   
4  10.6048  2.9890   ...      4.2259   9.1723   1.2835   3.3778  19.5542   

   var_195  var_196  var_197  var_198  var_199  
0   2.4669   4.3654  10.7200  15.4722  -8.7197  
1   0.4773  -1.4852   9.8714  19.1293 -20.9760  
2   2.1281  -7.1086   7.0618  19.8956 -23.1794  
3   3.1656   3.9567   9.2295  13.0168  -4.2108  
4  -0.2860  -5.1612   7.2882  13.9260  -9.1846  

[5 rows x 201 columns]

In [118]:
x_test=test

In [119]:
x_test.drop('ID_code',axis=1,inplace=True)

In [120]:
x_test=x_test.values

In [121]:
x_test

array([[ 11.0656,   7.7798,  12.9536, ...,  10.72  ,  15.4722,  -8.7197],
       [  8.5304,   1.2543,  11.3047, ...,   9.8714,  19.1293, -20.976 ],
       [  5.4827, -10.3581,  10.1407, ...,   7.0618,  19.8956, -23.1794],
       ...,
       [ 11.636 ,   2.2769,  11.2074, ...,   9.1933,  11.7905, -22.2762],
       [ 13.5745,  -0.5134,  13.6584, ...,   8.1079,   8.7735,  -0.2122],
       [ 10.4664,   1.807 ,  10.2277, ...,  10.3378,  14.334 ,  -7.7094]])

In [122]:
principal_compo=pc.fit_transform(x_train)

In [123]:
principal_compo

array([[ -5.60609426, -23.84633744],
       [ 34.8778511 ,  11.71504088],
       [ -4.78943466,  -0.47180502],
       ...,
       [ 36.84254689,   7.54866561],
       [ 30.23105056, -24.05604005],
       [ -5.99401371,   7.36676967]])

In [124]:
pc_pred_test=log_reg.predict(principal_compo)

In [125]:
test['Predicted target']=pc_pred_test

In [126]:
test.head()

var_0    var_1    var_2   var_3    var_4   var_5   var_6    var_7  \
0  11.0656   7.7798  12.9536  9.4292  11.4327 -2.3805  5.8493  18.2675   
1   8.5304   1.2543  11.3047  5.1858   9.1974 -4.0117  6.0196  18.6316   
2   5.4827 -10.3581  10.1407  7.0479  10.2628  9.8052  4.8950  20.2537   
3   8.5374  -1.3222  12.0220  6.5749   8.8458  3.1744  4.9397  20.5660   
4  11.7058  -0.1327  14.1295  7.7506   9.1035 -8.5848  6.8595  10.6048   

    var_8   var_9        ...         var_191  var_192  var_193  var_194  \
0  2.1337  8.8100        ...         11.8495  -1.4300   2.4508  13.7112   
1 -4.4131  5.9739        ...          8.8349   0.9403  10.1282  15.5765   
2  1.5233  8.3442        ...         10.9935   1.9803   2.1800  12.9813   
3  3.3755  7.4578        ...          9.0766   1.6580   3.5813  15.1874   
4  2.9890  7.1437        ...          9.1723   1.2835   3.3778  19.5542   

   var_195  var_196  var_197  var_198  var_199  Predicted target  
0   2.4669   4.3654  10.7200  15.4722  -8.7197                 0  
1   0.4773  -1.4852   9.8714  19.1293 -20.9760                 0  
2   2.1281  -7.1086   7.0618  19.8956 -23.1794                 0  
3   3.1656   3.9567   9.2295  13.0168  -4.2108                 0  
4  -0.2860  -5.1612   7.2882  13.9260  -9.1846                 0  

[5 rows x 201 columns]

## Following same steps we predicted for test dataset.